# CircleCI reusable commands demo
defaults: docker_image:
  - image: cimg/node:19.5.0
  

version 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output

  
  
